### PR TITLE
OCP multi-payload packaging changes

### PR DESCRIPTION
**Pull request by dccurtis**
New multiple payload OCP packaging changes were introduced here: https://github.com/project-koku/koku/pull/2115

Corresponding nise changes were made here: https://github.com/project-koku/nise/pull/225

**Testing**
1. Generate large csv report files with nise.
2. Copy csv file to a staging directory
3. Run korekuta package_report.py script so that it splits file into seperate payloads.
4. Extract two payloads and verify the manifest files contain both file names in the files list as well as the right file numbers
5. Merge two CSV files and diff with original file
6. Run korekuta package_report.py script so that the file is not split.
7. Extract payload and examine contents
8. Verify single payload csv to original.
9. Run create_package.py against an empty directory and ensure it handles it gracefully.

**Test Results**
[korekuta_split_change_ut.txt](https://github.com/project-koku/korekuta-operator/files/4611370/korekuta_split_change_ut.txt)

### CODE REVIEW

**Comment by chambridge** [comment]
Since we have existing customers, we should probably look at releasing a new version.
@adberglund  opinion?

**Comment by chambridge** [comment]
Also I'd suggest, if possible, similar changes be made to korekuta. Or we officially archive that project (which I'm in favor of).

**Comment by adberglund** [comment]
@chambridge I figured we'd release a new version, so I am in favor. I also like the idea of archiving korekuta. Documentation and UI all indicate use of the operator, yes? If so, I don't think we lose anything by not continuing to support korekuta.

**Comment by chambridge** [comment]
Yes, everything (docs & sources UI) points to the operator flow.

**Pull request merged**
